name: Call Reusable Workflow
on:
  push:
    branches:
      - main

jobs:
  use-reusable:
    uses: Gummybird-Maker/2402-first-repo/.github/workflows/reusable-test.yaml@master
    with:
      cool_var: "amazing"
